# Generated by Django 5.2.5 on 2025-08-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
        migrations.AddField(
            model_name='question',
            name='course_name',
            field=models.CharField(default='Dental module', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/explanations/'),
        ),
        migrations.AddField(
            model_name='question',
            name='module_name',
            field=models.CharField(default='Dental module', max_length=100),
            preserve_default=False,
        ),
    ]
